/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MatrixMultiplier;

public class App {
    public static void multiplyMatrix(int [][] a, int [][] b, int size) {
        int[][] c = new int[size][size];  
        for(int i=0;i<size;i++){  
            for(int j=0;j<size;j++){  
                c[i][j]=0;    
                for(int k=0;k<size;k++){    
                    c[i][j]+=a[i][k]*b[k][j];    
                }
                System.out.print(c[i][j]+" ");  
            }
            System.out.println();
        }  
    }

    public static void main(String[] args) {
    	long startTime = System.nanoTime();
    	int size = Integer.parseInt(args[0]);
    	if(size <= 1 || size >= 10000){
    		System.out.print("Size should be valid (from 1 to 10000).\n");
    	}else{
    		matrixReader mtx = new matrixReader();
    		int [][] firstMatrix = mtx.getMatrix(args[1], size);
    		int [][] secondMatrix = mtx.getMatrix(args[2], size);
    		multiplyMatrix(firstMatrix, secondMatrix, size);
    	}
    	long stopTime = System.nanoTime();
    	double elapsedTimeInSecond = (double) (stopTime - startTime) / 1000000000;
		System.out.println("Execution time: " + elapsedTimeInSecond);	
    }
}
